//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoPaso1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.dirEnteregas = new HashSet<dirEnterega>();
            this.Orden_del_cliente = new HashSet<Orden_del_cliente>();
        }
    
        public int Id_clente { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string calle_1 { get; set; }
        public string colonia_1 { get; set; }
        public string estado { get; set; }
        public string num_tarjeta_credito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dirEnterega> dirEnteregas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_del_cliente> Orden_del_cliente { get; set; }
    }
}
