//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoPaso1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class contextTienda : DbContext
    {
        public contextTienda()
            : base("name=contextTienda")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Paqueteria> Paqueterias { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<dirEnterega> dirEnteregas { get; set; }
        public virtual DbSet<Orden_del_cliente> Orden_del_cliente { get; set; }
        public virtual DbSet<Orden_Producto> Orden_Producto { get; set; }
    }
}
