//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoPaso1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_del_cliente
    {
        public int Id_orden_del_cliente { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string num_confirmacion { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_dirEntrega { get; set; }
        public Nullable<int> id_paqueteria { get; set; }
        public string num_guia { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual dirEnterega dirEnterega { get; set; }
        public virtual Paqueteria Paqueteria { get; set; }
    }
}
