//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccessoPaso1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paqueteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paqueteria()
        {
            this.Orden_del_cliente = new HashSet<Orden_del_cliente>();
        }
    
        public int Id_paqueteria { get; set; }
        public string nombre { get; set; }
        public string rfc { get; set; }
        public string tel { get; set; }
        public string web { get; set; }
        public string direccion { get; set; }
        public string contacto { get; set; }
        public string telContacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_del_cliente> Orden_del_cliente { get; set; }
    }
}
